name: cyborg-api-backend
version: '3'
services:
  api:
    container_name: cyborg-api-container
    image: cyborg-api:latest
    build: .
    entrypoint: [bash, -c, "source ~/.nvm/nvm.sh && npm run fastapi-dev"]
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_SERVER=redis
    networks:
      - cyborg-network
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - cyborg-network

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cyborg-network

volumes:
  postgres_data:

networks:
  cyborg-network:
