version: '3'
services:
  api:
    container_name: cyborg-api-container
    build: .
    entrypoint: npm run fastapi-dev
    env_file:
      - .env
    ports:
      - '5555:5555'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyborg_app
volumes:
  postgres_data:
# networks:
#   default:
#     external:
#       name: cyborg-network
