"""Initial migration

Revision ID: bca9d3dc72a0
Revises: 
Create Date: 2024-10-24 03:07:17.321796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca9d3dc72a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_configurations')
    op.drop_table('users')
    op.drop_table('game_statuses')
    op.drop_table('game_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_states',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id', 'step', name='game_states_pkey')
    )
    op.create_table('game_statuses',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('final_reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id', name='game_statuses_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
    )
    op.create_table('game_configurations',
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('red_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blue_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wrapper', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id', name='game_configurations_pkey')
    )
    # ### end Alembic commands ###
