"""Add createdAt column to game_configurations

Revision ID: d1579c4b8616
Revises: 97c6165b9ff0
Create Date: 2024-10-28 20:40:54.995613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1579c4b8616'
down_revision: Union[str, None] = '97c6165b9ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'game_configurations',
        sa.Column(
            'createdAt',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now()
        )
    )
    
def downgrade() -> None:
    op.drop_column('game_configurations', 'createdAt')
    
# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('game_configurations')
#     op.drop_table('users')
#     op.drop_table('game_states')
#     op.drop_table('game_summary')
#     op.drop_table('game_statuses')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('game_statuses',
#     sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('final_reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['game_id'], ['game_configurations.game_id'], name='game_statuses_game_id_fkey'),
#     sa.PrimaryKeyConstraint('game_id', name='game_statuses_pkey')
#     )
#     op.create_table('game_summary',
#     sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('final_reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['game_id'], ['game_configurations.game_id'], name='game_summary_game_id_fkey'),
#     sa.PrimaryKeyConstraint('game_id', name='game_summary_pkey')
#     )
#     op.create_table('game_states',
#     sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['game_id'], ['game_configurations.game_id'], name='game_states_game_id_fkey'),
#     sa.PrimaryKeyConstraint('game_id', 'step', name='game_states_pkey')
#     )
#     op.create_table('users',
#     sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
#     postgresql_ignore_search_path=False
#     )
#     op.create_table('game_configurations',
#     sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('red_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('blue_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('wrapper', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='game_configurations_user_id_fkey'),
#     sa.PrimaryKeyConstraint('game_id', name='game_configurations_pkey')
#     )
#     # ### end Alembic commands ###
